services:
  frontend:
    build:
      context: ../muscloot-frontend
      dockerfile: ./Dockerfile
    container_name: muscloot-frontend
    restart: always
    environment:
      - NEXT_PUBLIC_SITE_URL=${FRONTEND_NEXT_PUBLIC_SITE_URL}
      - AUTH_SERVICE_URL=${FRONTEND_AUTH_SERVICE_URL}
      - USER_SERVICE_URL=${FRONTEND_USER_SERVICE_URL}
      - WORKOUT_SERVICE_URL=${FRONTEND_WORKOUT_SERVICE_URL}
    ports:
      - "${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}"

  auth-server:
    build:
      context: ../auth-service
      dockerfile: ./build/auth/Dockerfile
    container_name: muscloot-auth-server
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${AUTH_SERVER_CONTAINER_PORT}
      - AUTH0_BASE_URL=${AUTH0_BASE_URL}
      - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
      - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    ports:
      - "${AUTH_SERVER_HOST_PORT}:${AUTH_SERVER_CONTAINER_PORT}"

  auth-grpc-gateway:
    build:
      context: ../auth-service
      dockerfile: ./build/gateway/Dockerfile
    container_name: muscloot-auth-grpc-gateway
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${AUTH_GRPC_GATEWAY_CONTAINER_PORT}
      - SERVER_HOST=${AUTH_SERVER_HOST}
      - SERVER_PORT=${AUTH_SERVER_CONTAINER_PORT}
    ports:
      - "${AUTH_GRPC_GATEWAY_HOST_PORT}:${AUTH_GRPC_GATEWAY_CONTAINER_PORT}"

  user-server:
    build:
      context: ../user-service
      dockerfile: ./build/user/Dockerfile
    container_name: muscloot-user-server
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${USER_SERVER_CONTAINER_PORT}
      - DB_HOST=${USER_DB_HOST}
      - DB_USER=${USER_DB_USER}
      - DB_PASSWORD=${USER_DB_PASSWORD}
      - DB_NAME=${USER_DB_NAME}
      - DB_PORT=${USER_DB_CONTAINER_PORT}
      - DB_SSL_MODE=${USER_DB_SSL_MODE}
      - AUTH_SERVICE_HOST=${AUTH_SERVER_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVER_CONTAINER_PORT}
    depends_on:
      user-db:
        condition: service_healthy
    ports:
      - "${USER_SERVER_HOST_PORT}:${USER_SERVER_CONTAINER_PORT}"

  user-grpc-gateway:
    build:
      context: ../user-service
      dockerfile: ./build/gateway/Dockerfile
    container_name: muscloot-user-grpc-gateway
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${USER_GRPC_GATEWAY_CONTAINER_PORT}
      - SERVER_HOST=${USER_SERVER_HOST}
      - SERVER_PORT=${USER_SERVER_CONTAINER_PORT}
    ports:
      - "${USER_GRPC_GATEWAY_HOST_PORT}:${USER_GRPC_GATEWAY_CONTAINER_PORT}"

  workout-server:
    build:
      context: ../workout-service
      dockerfile: ./build/workout/Dockerfile
    container_name: muscloot-workout-server
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${WORKOUT_SERVER_CONTAINER_PORT}
      - DB_HOST=${WORKOUT_DB_HOST}
      - DB_USER=${WORKOUT_DB_USER}
      - DB_PASSWORD=${WORKOUT_DB_PASSWORD}
      - DB_NAME=${WORKOUT_DB_NAME}
      - DB_PORT=${WORKOUT_DB_CONTAINER_PORT}
      - DB_SSL_MODE=${WORKOUT_DB_SSL_MODE}
      - AUTH_SERVICE_HOST=${AUTH_SERVER_HOST}
      - AUTH_SERVICE_PORT=${AUTH_SERVER_CONTAINER_PORT}
      - USER_SERVICE_HOST=${USER_SERVER_HOST}
      - USER_SERVICE_PORT=${USER_SERVER_CONTAINER_PORT}
    depends_on:
      workout-db:
        condition: service_healthy
    ports:
      - "${WORKOUT_SERVER_HOST_PORT}:${WORKOUT_SERVER_CONTAINER_PORT}"

  workout-grpc-gateway:
    build:
      context: ../workout-service
      dockerfile: ./build/gateway/Dockerfile
    container_name: muscloot-workout-grpc-gateway
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${WORKOUT_GRPC_GATEWAY_CONTAINER_PORT}
      - SERVER_HOST=${WORKOUT_SERVER_HOST}
      - SERVER_PORT=${WORKOUT_SERVER_CONTAINER_PORT}
    ports:
      - "${WORKOUT_GRPC_GATEWAY_HOST_PORT}:${WORKOUT_GRPC_GATEWAY_CONTAINER_PORT}"

  logging-server:
    build:
      context: ../logging-service
      dockerfile: ./Dockerfile
      secrets:
        - npmrc
    container_name: muscloot-logging-server
    restart: always
    environment:
      - ENV=${ENV}
      - PORT=${LOGGING_SERVER_CONTAINER_PORT}
      - DB_URL=${LOGGING_DB_URL}
      - AUTH_SERVICE_HOST=${AUTH_GRPC_GATEWAY_HOST}
      - AUTH_SERVICE_PORT=${AUTH_GRPC_GATEWAY_CONTAINER_PORT}
    depends_on:
      logging-db:
        condition: service_healthy
    ports:
      - "${LOGGING_SERVER_HOST_PORT}:${LOGGING_SERVER_CONTAINER_PORT}"

  user-db:
    image: postgres:17
    container_name: muscloot-user-db
    restart: always
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "${USER_DB_HOST_PORT}:${USER_DB_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - muscloot-user-db-data:/var/lib/postgresql/data

  workout-db:
    image: postgres:17
    container_name: muscloot-workout-db
    restart: always
    environment:
      POSTGRES_DB: ${WORKOUT_DB_NAME}
      POSTGRES_USER: ${WORKOUT_DB_USER}
      POSTGRES_PASSWORD: ${WORKOUT_DB_PASSWORD}
    ports:
      - "${WORKOUT_DB_HOST_PORT}:${WORKOUT_DB_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${WORKOUT_DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - muscloot-workout-db-data:/var/lib/postgresql/data

  logging-db:
    image: postgres:17
    container_name: muscloot-logging-db
    restart: always
    environment:
      POSTGRES_DB: ${LOGGING_DB_NAME}
      POSTGRES_USER: ${LOGGING_DB_USER}
      POSTGRES_PASSWORD: ${LOGGING_DB_PASSWORD}
    ports:
      - "${LOGGING_DB_HOST_PORT}:${LOGGING_DB_CONTAINER_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LOGGING_DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - muscloot-logging-db-data:/var/lib/postgresql/data

volumes:
  muscloot-user-db-data:
  muscloot-workout-db-data:
  muscloot-logging-db-data:

secrets:
  npmrc:
    file: .npmrc